name: Publish Python Package

on:
  release:
    types: [created]

jobs:
  build-n-publish:
    name: Build and publish Python ðŸ distributions ðŸ“¦ to PyPI
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2.2.2
      with:
        python-version: 3.9

    - name: Install Poetry
      run: |
        pip install poetry==1.3.2
        poetry self add "poetry-dynamic-versioning[plugin]"

    - name: Install project dependencies
      run: poetry install --no-interaction

#    - name: Install yq
#      env:
#        YQ_VERSION: v4.30.5
#        YQ_BINARY: yq_linux_amd64
#      run: |
#        mkdir -p $HOME/.local/bin
#        wget https://github.com/mikefarah/yq/releases/download/$YQ_VERSION/$YQ_BINARY.tar.gz -O - | tar xz && mv $YQ_BINARY $HOME/.local/bin/yq
#        echo "$HOME/.local/bin" >> $GITHUB_PATH

    - name: Generate project files
      run: |
        make clean schema_cleanup src/nmdc_submission_schema/schema/nmdc_submission_schema.yaml
        poetry dynamic-versioning
        make gen-project

    - name: Build source and wheel archives
      run: poetry build

    - name: Publish distribution ðŸ“¦ to PyPI
      uses: pypa/gh-action-pypi-publish@v1.2.2
      with:
        user: __token__
        password: ${{ secrets.PYPI_PASSWORD }}
